memory_limit = 512M
date.timezone = UTC
expose_php = 0

opcache.enable = 1
; code 已打包進 image，不需檢查檔案異動
opcache.validate_timestamps = 0
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000

realpath_cache_size = 4096K
realpath_cache_ttl = 600
